language: php

php:
- 5.5

env:
- RUNJOB=eslint
- RUNJOB=qunit

before_script:
  - nvm install 4

script: bash ./build/travis/script.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
