language: php

php:
- 5.5

before_script:
  - nvm install 4
  - npm install

script:
  - npm test

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: never
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

