language: node_js

node_js:
- 10
- 12
- 14

before_script:
  - npm install

script:
  - npm test

notifications:
  irc:
    channels:
      - "irc.libera.chat#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

